Incident report
LIHI-seattle/dashboard pull request #22
Opened 2020-07-09 19:53 UTC by aashnasheth

2020-07-12 23:59 UTC, kushaljh requested changes

2020-07-12 23:59 UTC, kushaljh commented on src/IncidentReportView.js
> +import {Container, Row, Col} from 'reactstrap';
You can import this from react-bootstrap which is already used elsewhere as well

https://react-bootstrap.github.io/layout/grid/

2020-07-12 23:59 UTC, kushaljh commented on src/IncidentReportView.js
> +            //value: event.label,
nit: remove

2020-07-12 23:59 UTC, kushaljh commented on src/IncidentReportView.js
> +            body: JSON.stringify(data),
why is this in comments?

2020-07-12 23:59 UTC, kushaljh commented on src/ResidentDirectory.js
>  import Button from 'react-bootstrap/Button';
@aashnasheth 
See this for reference

I do believe that you can import multiple together as import { Card, Button } from 'react-bootstrap'; as well

2020-07-12 23:59 UTC, kushaljh commented on src/ResidentDirectory.js
> +        // console.log("reupdating data");
Maybe remove this altogether now?

2020-07-12 23:59 UTC, kushaljh commented on src/ResidentDirectory.js
> +                        {/* {console.log(this.state.residents)} */}
same here

2020-07-12 23:59 UTC, kushaljh commented on src/ResidentDirectory.js
> +                                        <li>Current Residence: house {this.state.data.HOUSE_NUM} in {this.state.data.NAME} village</li>
Name is Village Name? 
Doesnt sound like the correct variable name.

2020-07-13 00:03 UTC, daniellee0 approved these changes

2020-07-13 00:03 UTC, daniellee0 commented on src/ResidentDirectory.js
> +                this.reupdateData();
Which block is being used to handle a 200 response status?

2020-07-13 00:03 UTC, daniellee0 commented on src/ResidentDirectory.js
> +                    data: '',
- Should have a default value in constructor for clarity. 
- Naming is obscure.

2020-07-13 01:05 UTC, kushaljh approved these changes

2020-07-13 01:08 UTC, merged